# Generated by Django 3.1.5 on 2021-04-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('dob', models.DateField(verbose_name='date published')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='contact_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='hotels',
            name='email_id',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
